# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8

jobs:
  test:
    <<: *defaults  
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - run:
          name: Run tests
          command: yarn test
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Build
          command: yarn build
      - run:
          name: Publish package
          command: npm publish
            
workflows:
  version: 2
  main:
    jobs:
      - test:
          filters:
            tags:
              ignore: /^v.*/
      - release:
          requires:
            - test
          filters:
            tags:
              only: /^src-v.*/
            branches:
              ignore: /.*/